### ISSUE TITLE
The freeze at the beginning of "(1) 1481 Bad Apple!! (Original Ver.)" on s19 offsets the entire chart after, making it basically unplayable.

### ISSUE THREAD

**Issue by ZackNyx** [piulin/piured#2]

**Comment by piulin** [comment]
The problem relies on the use of WARPS in the SSC file, which at the moment are unsupported by the sequencer. Therefore, levels using unsupported tricks (i.e. STOPS, DELAYS, and WARPS) are likely to be unplayable. Currently, the demo webpage warns you about this if the selected level uses unsupported features.
