### ISSUE TITLE
Local deploy

### ISSUE THREAD

**Issue by ignaciora** [piulin/piured#3]
Podrías decirme si es posible conseguir las canciones para hacer un deploy local para uso personal únicamente? Desde ya muchas gracias! nacho.rodriguez.a@gmail.com

**Comment by mHalo** [comment]
Hello,I need this too.Thanks a lot.  heng21@yeah.net


![image](https://github.com/user-attachments/assets/d5b19ae4-9e05-4a76-bb08-69b84df3c761)

**Comment by piulin** [comment]
@mHalo you need to provide your own list of songs.
